package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * CorveiculoId generated by hbm2java
 */
@Entity
public class CorVeiculo implements java.io.Serializable {

	private Integer tcecodigo;
	private String tcedescricao;
	private String tceatualiza;


	@Column(name = "tcecodigo")
	public Integer getTcecodigo() {
		return this.tcecodigo;
	}

	public void setTcecodigo(Integer tcecodigo) {
		this.tcecodigo = tcecodigo;
	}

	@Column(name = "tcedescricao", length = 8)
	public String getTcedescricao() {
		return this.tcedescricao;
	}

	public void setTcedescricao(String tcedescricao) {
		this.tcedescricao = tcedescricao;
	}

	@Column(name = "tceatualiza", length = 1)
	public String getTceatualiza() {
		return this.tceatualiza;
	}

	public void setTceatualiza(String tceatualiza) {
		this.tceatualiza = tceatualiza;
	}

}
