package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * LocalbrId generated by hbm2java
 */
@Entity
public class LocalBr implements java.io.Serializable {

	private Integer lbrid;
	private String lbruf;
	private Integer lbrbr;
	private Integer lbrkm;
	private String lbrlatitude;
	private String lbrlongitude;
	private Integer lbrpnvid;
	private String lbratualiza;

	
	@Column(name = "lbrid")
	public Integer getLbrid() {
		return this.lbrid;
	}

	public void setLbrid(Integer lbrid) {
		this.lbrid = lbrid;
	}

	@Column(name = "lbruf", length = 2)
	public String getLbruf() {
		return this.lbruf;
	}

	public void setLbruf(String lbruf) {
		this.lbruf = lbruf;
	}

	@Column(name = "lbrbr")
	public Integer getLbrbr() {
		return this.lbrbr;
	}

	public void setLbrbr(Integer lbrbr) {
		this.lbrbr = lbrbr;
	}

	@Column(name = "lbrkm")
	public Integer getLbrkm() {
		return this.lbrkm;
	}

	public void setLbrkm(Integer lbrkm) {
		this.lbrkm = lbrkm;
	}

	@Column(name = "lbrlatitude", length = 6)
	public String getLbrlatitude() {
		return this.lbrlatitude;
	}

	public void setLbrlatitude(String lbrlatitude) {
		this.lbrlatitude = lbrlatitude;
	}

	@Column(name = "lbrlongitude", length = 6)
	public String getLbrlongitude() {
		return this.lbrlongitude;
	}

	public void setLbrlongitude(String lbrlongitude) {
		this.lbrlongitude = lbrlongitude;
	}

	@Column(name = "lbrpnvid")
	public Integer getLbrpnvid() {
		return this.lbrpnvid;
	}

	public void setLbrpnvid(Integer lbrpnvid) {
		this.lbrpnvid = lbrpnvid;
	}

	@Column(name = "lbratualiza", length = 1)
	public String getLbratualiza() {
		return this.lbratualiza;
	}

	public void setLbratualiza(String lbratualiza) {
		this.lbratualiza = lbratualiza;
	}
}
