package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MarcadeveiculoId generated by hbm2java
 */

@Entity
@Table(name = "marcadeveiculo")
public class MarcaVeiculo implements java.io.Serializable {

	private Integer tmvcodigo;
	private String tmvdescricao;
	private String tmvatualiza;


	@Column(name = "tmvcodigo")
	public Integer getTmvcodigo() {
		return this.tmvcodigo;
	}

	public void setTmvcodigo(Integer tmvcodigo) {
		this.tmvcodigo = tmvcodigo;
	}

	@Column(name = "tmvdescricao", length = 60)
	public String getTmvdescricao() {
		return this.tmvdescricao;
	}

	public void setTmvdescricao(String tmvdescricao) {
		this.tmvdescricao = tmvdescricao;
	}

	@Column(name = "tmvatualiza", length = 1)
	public String getTmvatualiza() {
		return this.tmvatualiza;
	}

	public void setTmvatualiza(String tmvatualiza) {
		this.tmvatualiza = tmvatualiza;
	}

}
