package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * MunicipioId generated by hbm2java
 */
@Entity
public class Municipio implements java.io.Serializable {

	private Integer tmucodigo;
	private String tmudenominacao;
	private String tmuuf;

	@Column(name = "tmucodigo")
	public Integer getTmucodigo() {
		return this.tmucodigo;
	}

	public void setTmucodigo(Integer tmucodigo) {
		this.tmucodigo = tmucodigo;
	}

	@Column(name = "tmudenominacao", length = 32)
	public String getTmudenominacao() {
		return this.tmudenominacao;
	}

	public void setTmudenominacao(String tmudenominacao) {
		this.tmudenominacao = tmudenominacao;
	}

	@Column(name = "tmuuf", length = 2)
	public String getTmuuf() {
		return this.tmuuf;
	}

	public void setTmuuf(String tmuuf) {
		this.tmuuf = tmuuf;
	}
}
