package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * OcorrenciapessoaId generated by hbm2java
 */
@Entity
public class OcorrenciaPessoa implements java.io.Serializable {

	private Integer opeid;
	private Integer opeocoid;
	private Integer opepesid;
	private String opeportenumero;
	private String opeportevalidade;
	private Integer opettecodigo;
	private String openaoident;
	private String opeestrangeiro;
	private String opeanexo;
	private String opecondalegadas;
	private Pessoa pessoa;
	private TipoEnvolvido tipoEnvolvido;
	private Ocorrencia ocorrencia;
	
	
	public Integer getOpepesid() {
		return opepesid;
	}

	public void setOpepesid(Integer opepesid) {
		this.opepesid = opepesid;
	}

	@ManyToOne
	@JoinColumn(name="opeocoid")
	public Ocorrencia getOcorrencia() {
		return ocorrencia;
	}

	public void setOcorrencia(Ocorrencia ocorrencia) {
		this.ocorrencia = ocorrencia;
	}

	@ManyToOne
	@JoinColumn(name="opepesid")
    public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@ManyToOne
	@JoinColumn(name="opettecodigo")
	public TipoEnvolvido getTipoEnvolvido() {
		return tipoEnvolvido;
	}

	public void setTipoEnvolvido(TipoEnvolvido tipoEnvolvido) {
		this.tipoEnvolvido = tipoEnvolvido;
	}


	@Column(name = "opeid")
	public Integer getOpeid() {
		return this.opeid;
	}

	public void setOpeid(Integer opeid) {
		this.opeid = opeid;
	}

	@Column(name = "opeocoid")
	public Integer getOpeocoid() {
		return this.opeocoid;
	}

	public void setOpeocoid(Integer opeocoid) {
		this.opeocoid = opeocoid;
	}

	@Column(name = "opeportenumero", length = 6)
	public String getOpeportenumero() {
		return this.opeportenumero;
	}

	public void setOpeportenumero(String opeportenumero) {
		this.opeportenumero = opeportenumero;
	}

	@Column(name = "opeportevalidade", length = 6)
	public String getOpeportevalidade() {
		return this.opeportevalidade;
	}

	public void setOpeportevalidade(String opeportevalidade) {
		this.opeportevalidade = opeportevalidade;
	}

	@Column(name = "opettecodigo")
	public Integer getOpettecodigo() {
		return this.opettecodigo;
	}

	public void setOpettecodigo(Integer opettecodigo) {
		this.opettecodigo = opettecodigo;
	}

	@Column(name = "openaoident", length = 1)
	public String getOpenaoident() {
		return this.openaoident;
	}

	public void setOpenaoident(String openaoident) {
		this.openaoident = openaoident;
	}

	@Column(name = "opeestrangeiro", length = 1)
	public String getOpeestrangeiro() {
		return this.opeestrangeiro;
	}

	public void setOpeestrangeiro(String opeestrangeiro) {
		this.opeestrangeiro = opeestrangeiro;
	}

	@Column(name = "opeanexo", length = 1)
	public String getOpeanexo() {
		return this.opeanexo;
	}

	public void setOpeanexo(String opeanexo) {
		this.opeanexo = opeanexo;
	}

	@Column(name = "opecondalegadas", length = 6)
	public String getOpecondalegadas() {
		return this.opecondalegadas;
	}

	public void setOpecondalegadas(String opecondalegadas) {
		this.opecondalegadas = opecondalegadas;
	}
}
