package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * OcorrenciaveiculoId generated by hbm2java
 */
@Entity
public class OcorrenciaVeiculo implements java.io.Serializable {

	private Integer ocvid;
	private Integer ocvocoid;
	private Integer ocvveiid;
	private List<Ocorrencia> ocorrencias = new ArrayList<Ocorrencia>();
	private List<Veiculo> veiculos = new ArrayList<Veiculo>();
	
	@OneToMany(mappedBy="ocorrenciaVeiculo",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<Ocorrencia> getOcorrencias() {
		return ocorrencias;
	}

	public void setOcorrencias(List<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

	@OneToMany(mappedBy="ocorrenciaVeiculo",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<Veiculo> getVeiculos() {
		return veiculos;
	}

	public void setVeiculos(List<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

	@Column(name = "ocvid")
	public Integer getOcvid() {
		return this.ocvid;
	}

	public void setOcvid(Integer ocvid) {
		this.ocvid = ocvid;
	}

	@Column(name = "ocvocoid")
	public Integer getOcvocoid() {
		return this.ocvocoid;
	}

	public void setOcvocoid(Integer ocvocoid) {
		this.ocvocoid = ocvocoid;
	}

	@Column(name = "ocvveiid")
	public Integer getOcvveiid() {
		return this.ocvveiid;
	}

	public void setOcvveiid(Integer ocvveiid) {
		this.ocvveiid = ocvveiid;
	}
}
