package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * OcorrenciaId generated by hbm2java
 */
@Entity
public class Ocorrencia implements java.io.Serializable {

	private Integer ocoid;
	private Integer ocolocal;
	private String ocostatus;
	private String ocomunicipio;
	private Integer ocosentido;
	private String ocodataocorrencia;
	private String ocodataregistro;
	private String ocotipo;
	private Integer ococomid;
	private String ocoidorigem;
	private String ocodatafim;
	private List<OcorrenciaPessoa> ocorrenciasPessoa = new ArrayList<OcorrenciaPessoa>();
	private OcorrenciaVeiculo ocorrenciaVeiculo;
	private OcorrenciaAcidente ocorrenciaAcidente;


	@ManyToOne
	@JoinColumn(name="oacocoid")
	public OcorrenciaAcidente getOcorrenciaAcidente() {
		return ocorrenciaAcidente;
	}

	public void setOcorrenciaAcidente(OcorrenciaAcidente ocorrenciaAcidente) {
		this.ocorrenciaAcidente = ocorrenciaAcidente;
	}

	@ManyToOne
  	@JoinColumn(name="ocvocoid")
    public OcorrenciaVeiculo getOcorrenciaVeiculo() {
		return ocorrenciaVeiculo;
	}

	public void setOcorrenciaVeiculo(OcorrenciaVeiculo ocorrenciaVeiculo) {
		this.ocorrenciaVeiculo = ocorrenciaVeiculo;
	}
	
	
	@OneToMany(mappedBy = "ocorrencia",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<OcorrenciaPessoa> getOcorrenciasPessoa() {
		return ocorrenciasPessoa;
	}

	public void setOcorrenciasPessoa(List<OcorrenciaPessoa> ocorrenciasPessoa) {
		this.ocorrenciasPessoa = ocorrenciasPessoa;
	}

	@Column(name = "ocoid")
	public Integer getOcoid() {
		return this.ocoid;
	}

	public void setOcoid(Integer ocoid) {
		this.ocoid = ocoid;
	}

	@Column(name = "ocolocal")
	public Integer getOcolocal() {
		return this.ocolocal;
	}

	public void setOcolocal(Integer ocolocal) {
		this.ocolocal = ocolocal;
	}

	@Column(name = "ocostatus", length = 1)
	public String getOcostatus() {
		return this.ocostatus;
	}

	public void setOcostatus(String ocostatus) {
		this.ocostatus = ocostatus;
	}

	@Column(name = "ocomunicipio", length = 6)
	public String getOcomunicipio() {
		return this.ocomunicipio;
	}

	public void setOcomunicipio(String ocomunicipio) {
		this.ocomunicipio = ocomunicipio;
	}

	@Column(name = "ocosentido")
	public Integer getOcosentido() {
		return this.ocosentido;
	}

	public void setOcosentido(Integer ocosentido) {
		this.ocosentido = ocosentido;
	}

	@Column(name = "ocodataocorrencia", length = 19)
	public String getOcodataocorrencia() {
		return this.ocodataocorrencia;
	}

	public void setOcodataocorrencia(String ocodataocorrencia) {
		this.ocodataocorrencia = ocodataocorrencia;
	}

	@Column(name = "ocodataregistro", length = 19)
	public String getOcodataregistro() {
		return this.ocodataregistro;
	}

	public void setOcodataregistro(String ocodataregistro) {
		this.ocodataregistro = ocodataregistro;
	}

	@Column(name = "ocotipo", length = 2)
	public String getOcotipo() {
		return this.ocotipo;
	}

	public void setOcotipo(String ocotipo) {
		this.ocotipo = ocotipo;
	}

	@Column(name = "ococomid")
	public Integer getOcocomid() {
		return this.ococomid;
	}

	public void setOcocomid(Integer ococomid) {
		this.ococomid = ococomid;
	}

	@Column(name = "ocoidorigem", length = 6)
	public String getOcoidorigem() {
		return this.ocoidorigem;
	}

	public void setOcoidorigem(String ocoidorigem) {
		this.ocoidorigem = ocoidorigem;
	}

	@Column(name = "ocodatafim", length = 19)
	public String getOcodatafim() {
		return this.ocodatafim;
	}

	public void setOcodatafim(String ocodatafim) {
		this.ocodatafim = ocodatafim;
	}
}
