package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * PessoaId generated by hbm2java
 */
@Entity
public class Pessoa implements java.io.Serializable {

	private Integer pesid;
	private String pesdatanascimento;
	private String pesnaturalidade;
	private Integer pesnacionalidade;
	private String pessexo;
	private Integer pesteccodigo;
	private Integer pestgicodigo;
	private Integer pesmunicipio;
	private Integer pestopcodigo;
	private String pesmunicipioori;
	private Integer pespaisori;
	private String pesmunicipiodest;
	private Integer pespaisdest;
	private Veiculo veiculo;
	private String pesveiid;
	private Integer pesestadofisico;
	private String pescinto;
	private String pescapacete;
	private String peshabilitado;
	private String pessocorrido;
	private String pesdormindo;
	private String pesalcool;
	private String peskmpercorre;
	private String peshorapercorre;
	private String pescategcnh;
	private String pesufcnh;
	private Integer pespaiscnh;
	private String pesdatahabil;
	private String pesdatavalidade;
	private String pesidade;
	private String pesaltura;
	private String pespeso;
	private String pescicatriz;
	private String pestatuagem;
	private String pessinal;
	private String peslesao;
	private Integer pestcccodigo;
	private Integer pestctcodigo;
	private Integer pestclcodigo;
	private Integer pesoenid;
	private List<OcorrenciaPessoa> ocorrenciasPessoa = new ArrayList<OcorrenciaPessoa>();

	
	@OneToMany(mappedBy = "pessoa",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<OcorrenciaPessoa> getOcorrenciasPessoa() {
		return ocorrenciasPessoa;
	}

	public void setOcorrenciasPessoa(List<OcorrenciaPessoa> ocorrenciasPessoa) {
		this.ocorrenciasPessoa = ocorrenciasPessoa;
	}

	@Column(name = "pesid")
	public Integer getPesid() {
		return this.pesid;
	}

	public void setPesid(Integer pesid) {
		this.pesid = pesid;
	}

	@Column(name = "pesdatanascimento", length = 10)
	public String getPesdatanascimento() {
		return this.pesdatanascimento;
	}

	public void setPesdatanascimento(String pesdatanascimento) {
		this.pesdatanascimento = pesdatanascimento;
	}

	@Column(name = "pesnaturalidade", length = 5)
	public String getPesnaturalidade() {
		return this.pesnaturalidade;
	}

	public void setPesnaturalidade(String pesnaturalidade) {
		this.pesnaturalidade = pesnaturalidade;
	}

	@Column(name = "pesnacionalidade")
	public Integer getPesnacionalidade() {
		return this.pesnacionalidade;
	}

	public void setPesnacionalidade(Integer pesnacionalidade) {
		this.pesnacionalidade = pesnacionalidade;
	}

	@Column(name = "pessexo", length = 6)
	public String getPessexo() {
		return this.pessexo;
	}

	public void setPessexo(String pessexo) {
		this.pessexo = pessexo;
	}

	@Column(name = "pesteccodigo")
	public Integer getPesteccodigo() {
		return this.pesteccodigo;
	}

	public void setPesteccodigo(Integer pesteccodigo) {
		this.pesteccodigo = pesteccodigo;
	}

	@Column(name = "pestgicodigo")
	public Integer getPestgicodigo() {
		return this.pestgicodigo;
	}

	public void setPestgicodigo(Integer pestgicodigo) {
		this.pestgicodigo = pestgicodigo;
	}

	@Column(name = "pesmunicipio")
	public Integer getPesmunicipio() {
		return this.pesmunicipio;
	}

	public void setPesmunicipio(Integer pesmunicipio) {
		this.pesmunicipio = pesmunicipio;
	}

	@Column(name = "pestopcodigo")
	public Integer getPestopcodigo() {
		return this.pestopcodigo;
	}

	public void setPestopcodigo(Integer pestopcodigo) {
		this.pestopcodigo = pestopcodigo;
	}

	@Column(name = "pesmunicipioori", length = 5)
	public String getPesmunicipioori() {
		return this.pesmunicipioori;
	}

	public void setPesmunicipioori(String pesmunicipioori) {
		this.pesmunicipioori = pesmunicipioori;
	}

	@Column(name = "pespaisori")
	public Integer getPespaisori() {
		return this.pespaisori;
	}

	public void setPespaisori(Integer pespaisori) {
		this.pespaisori = pespaisori;
	}

	@Column(name = "pesmunicipiodest", length = 5)
	public String getPesmunicipiodest() {
		return this.pesmunicipiodest;
	}

	public void setPesmunicipiodest(String pesmunicipiodest) {
		this.pesmunicipiodest = pesmunicipiodest;
	}

	@Column(name = "pespaisdest")
	public Integer getPespaisdest() {
		return this.pespaisdest;
	}

	public void setPespaisdest(Integer pespaisdest) {
		this.pespaisdest = pespaisdest;
	}

	
	@OneToOne(mappedBy="pessoa")
	public Veiculo getVeiculo() {
		return veiculo;
	}

	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}
	
	@Column(name = "pesveiid")
	public String getPesveiid() {
		return pesveiid;
	}

	public void setPesveiid(String pesveiid) {
		this.pesveiid = pesveiid;
	}

	@Column(name = "pesestadofisico")
	public Integer getPesestadofisico() {
		return this.pesestadofisico;
	}

	

	public void setPesestadofisico(Integer pesestadofisico) {
		this.pesestadofisico = pesestadofisico;
	}

	@Column(name = "pescinto", length = 6)
	public String getPescinto() {
		return this.pescinto;
	}

	public void setPescinto(String pescinto) {
		this.pescinto = pescinto;
	}

	@Column(name = "pescapacete", length = 6)
	public String getPescapacete() {
		return this.pescapacete;
	}

	public void setPescapacete(String pescapacete) {
		this.pescapacete = pescapacete;
	}

	@Column(name = "peshabilitado", length = 6)
	public String getPeshabilitado() {
		return this.peshabilitado;
	}

	public void setPeshabilitado(String peshabilitado) {
		this.peshabilitado = peshabilitado;
	}

	@Column(name = "pessocorrido", length = 1)
	public String getPessocorrido() {
		return this.pessocorrido;
	}

	public void setPessocorrido(String pessocorrido) {
		this.pessocorrido = pessocorrido;
	}

	@Column(name = "pesdormindo", length = 1)
	public String getPesdormindo() {
		return this.pesdormindo;
	}

	public void setPesdormindo(String pesdormindo) {
		this.pesdormindo = pesdormindo;
	}

	@Column(name = "pesalcool", length = 6)
	public String getPesalcool() {
		return this.pesalcool;
	}

	public void setPesalcool(String pesalcool) {
		this.pesalcool = pesalcool;
	}

	@Column(name = "peskmpercorre", length = 6)
	public String getPeskmpercorre() {
		return this.peskmpercorre;
	}

	public void setPeskmpercorre(String peskmpercorre) {
		this.peskmpercorre = peskmpercorre;
	}

	@Column(name = "peshorapercorre", length = 6)
	public String getPeshorapercorre() {
		return this.peshorapercorre;
	}

	public void setPeshorapercorre(String peshorapercorre) {
		this.peshorapercorre = peshorapercorre;
	}

	@Column(name = "pescategcnh", length = 6)
	public String getPescategcnh() {
		return this.pescategcnh;
	}

	public void setPescategcnh(String pescategcnh) {
		this.pescategcnh = pescategcnh;
	}

	@Column(name = "pesufcnh", length = 6)
	public String getPesufcnh() {
		return this.pesufcnh;
	}

	public void setPesufcnh(String pesufcnh) {
		this.pesufcnh = pesufcnh;
	}

	@Column(name = "pespaiscnh")
	public Integer getPespaiscnh() {
		return this.pespaiscnh;
	}

	public void setPespaiscnh(Integer pespaiscnh) {
		this.pespaiscnh = pespaiscnh;
	}

	@Column(name = "pesdatahabil", length = 10)
	public String getPesdatahabil() {
		return this.pesdatahabil;
	}

	public void setPesdatahabil(String pesdatahabil) {
		this.pesdatahabil = pesdatahabil;
	}

	@Column(name = "pesdatavalidade", length = 10)
	public String getPesdatavalidade() {
		return this.pesdatavalidade;
	}

	public void setPesdatavalidade(String pesdatavalidade) {
		this.pesdatavalidade = pesdatavalidade;
	}

	@Column(name = "pesidade", length = 6)
	public String getPesidade() {
		return this.pesidade;
	}

	public void setPesidade(String pesidade) {
		this.pesidade = pesidade;
	}

	@Column(name = "pesaltura", length = 6)
	public String getPesaltura() {
		return this.pesaltura;
	}

	public void setPesaltura(String pesaltura) {
		this.pesaltura = pesaltura;
	}

	@Column(name = "pespeso", length = 6)
	public String getPespeso() {
		return this.pespeso;
	}

	public void setPespeso(String pespeso) {
		this.pespeso = pespeso;
	}

	@Column(name = "pescicatriz", length = 1)
	public String getPescicatriz() {
		return this.pescicatriz;
	}

	public void setPescicatriz(String pescicatriz) {
		this.pescicatriz = pescicatriz;
	}

	@Column(name = "pestatuagem", length = 1)
	public String getPestatuagem() {
		return this.pestatuagem;
	}

	public void setPestatuagem(String pestatuagem) {
		this.pestatuagem = pestatuagem;
	}

	@Column(name = "pessinal", length = 1)
	public String getPessinal() {
		return this.pessinal;
	}

	public void setPessinal(String pessinal) {
		this.pessinal = pessinal;
	}

	@Column(name = "peslesao", length = 1)
	public String getPeslesao() {
		return this.peslesao;
	}

	public void setPeslesao(String peslesao) {
		this.peslesao = peslesao;
	}

	@Column(name = "pestcccodigo")
	public Integer getPestcccodigo() {
		return this.pestcccodigo;
	}

	public void setPestcccodigo(Integer pestcccodigo) {
		this.pestcccodigo = pestcccodigo;
	}

	@Column(name = "pestctcodigo")
	public Integer getPestctcodigo() {
		return this.pestctcodigo;
	}

	public void setPestctcodigo(Integer pestctcodigo) {
		this.pestctcodigo = pestctcodigo;
	}

	@Column(name = "pestclcodigo")
	public Integer getPestclcodigo() {
		return this.pestclcodigo;
	}

	public void setPestclcodigo(Integer pestclcodigo) {
		this.pestclcodigo = pestclcodigo;
	}

	@Column(name = "pesoenid")
	public Integer getPesoenid() {
		return this.pesoenid;
	}

	public void setPesoenid(Integer pesoenid) {
		this.pesoenid = pesoenid;
	}
}
