package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipoobraId generated by hbm2java
 */
@Entity
public class TipoObra implements java.io.Serializable {

	private Integer ttbcodigo;
	private String ttbdescricao;
	private String ttbatualiza;


	@Column(name = "ttbcodigo")
	public Integer getTtbcodigo() {
		return this.ttbcodigo;
	}

	public void setTtbcodigo(Integer ttbcodigo) {
		this.ttbcodigo = ttbcodigo;
	}

	@Column(name = "ttbdescricao", length = 9)
	public String getTtbdescricao() {
		return this.ttbdescricao;
	}

	public void setTtbdescricao(String ttbdescricao) {
		this.ttbdescricao = ttbdescricao;
	}

	@Column(name = "ttbatualiza", length = 1)
	public String getTtbatualiza() {
		return this.ttbatualiza;
	}

	public void setTtbatualiza(String ttbatualiza) {
		this.ttbatualiza = ttbatualiza;
	}
}
