package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipocomunicacaoId generated by hbm2java
 */
@Entity
public class TipoComunicacao implements java.io.Serializable {

	private Integer tcocodigo;
	private String tcodescricao;
	private String tcoatualiza;

	@Column(name = "tcocodigo")
	public Integer getTcocodigo() {
		return this.tcocodigo;
	}

	public void setTcocodigo(Integer tcocodigo) {
		this.tcocodigo = tcocodigo;
	}

	@Column(name = "tcodescricao", length = 21)
	public String getTcodescricao() {
		return this.tcodescricao;
	}

	public void setTcodescricao(String tcodescricao) {
		this.tcodescricao = tcodescricao;
	}

	@Column(name = "tcoatualiza", length = 1)
	public String getTcoatualiza() {
		return this.tcoatualiza;
	}

	public void setTcoatualiza(String tcoatualiza) {
		this.tcoatualiza = tcoatualiza;
	}
}
