package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipocrimeId generated by hbm2java
 */
@Entity
public class TipoCrime implements java.io.Serializable {

	private Integer ttccodigo;
	private String ttcdescricao;
	private String ttcatualiza;

	@Column(name = "ttccodigo")
	public Integer getTtccodigo() {
		return this.ttccodigo;
	}

	public void setTtccodigo(Integer ttccodigo) {
		this.ttccodigo = ttccodigo;
	}

	@Column(name = "ttcdescricao", length = 32)
	public String getTtcdescricao() {
		return this.ttcdescricao;
	}

	public void setTtcdescricao(String ttcdescricao) {
		this.ttcdescricao = ttcdescricao;
	}

	@Column(name = "ttcatualiza", length = 1)
	public String getTtcatualiza() {
		return this.ttcatualiza;
	}

	public void setTtcatualiza(String ttcatualiza) {
		this.ttcatualiza = ttcatualiza;
	}
}
