package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipoveiculoId generated by hbm2java
 */
@Entity
public class TipoVeiculo implements java.io.Serializable {

	private Integer tvvcodigo;
	private String tvvdescricao;
	private String tvvatualiza;
	private String tvvrelacidente;
	private String tvvativo;


	@Column(name = "tvvcodigo")
	public Integer getTvvcodigo() {
		return this.tvvcodigo;
	}

	public void setTvvcodigo(Integer tvvcodigo) {
		this.tvvcodigo = tvvcodigo;
	}

	@Column(name = "tvvdescricao", length = 23)
	public String getTvvdescricao() {
		return this.tvvdescricao;
	}

	public void setTvvdescricao(String tvvdescricao) {
		this.tvvdescricao = tvvdescricao;
	}

	@Column(name = "tvvatualiza", length = 1)
	public String getTvvatualiza() {
		return this.tvvatualiza;
	}

	public void setTvvatualiza(String tvvatualiza) {
		this.tvvatualiza = tvvatualiza;
	}

	@Column(name = "tvvrelacidente", length = 6)
	public String getTvvrelacidente() {
		return this.tvvrelacidente;
	}

	public void setTvvrelacidente(String tvvrelacidente) {
		this.tvvrelacidente = tvvrelacidente;
	}

	@Column(name = "tvvativo", length = 1)
	public String getTvvativo() {
		return this.tvvativo;
	}

	public void setTvvativo(String tvvativo) {
		this.tvvativo = tvvativo;
	}
}
