package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TiporeceptorId generated by hbm2java
 */
@Entity
public class TipoReceptor implements java.io.Serializable {

	private Integer ttrcodigo;
	private String ttrdescricao;
	private String ttratualiza;
	private String ttrdelegacia;

	@Column(name = "ttrcodigo")
	public Integer getTtrcodigo() {
		return this.ttrcodigo;
	}

	public void setTtrcodigo(Integer ttrcodigo) {
		this.ttrcodigo = ttrcodigo;
	}

	@Column(name = "ttrdescricao", length = 31)
	public String getTtrdescricao() {
		return this.ttrdescricao;
	}

	public void setTtrdescricao(String ttrdescricao) {
		this.ttrdescricao = ttrdescricao;
	}

	@Column(name = "ttratualiza", length = 1)
	public String getTtratualiza() {
		return this.ttratualiza;
	}

	public void setTtratualiza(String ttratualiza) {
		this.ttratualiza = ttratualiza;
	}

	@Column(name = "ttrdelegacia", length = 6)
	public String getTtrdelegacia() {
		return this.ttrdelegacia;
	}

	public void setTtrdelegacia(String ttrdelegacia) {
		this.ttrdelegacia = ttrdelegacia;
	}
}
