package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * TipoacidenteId generated by hbm2java
 */
@Entity
public class TipoAcidente implements java.io.Serializable {

	private Integer ttacodigo;
	private String ttadescricao;
	private String ttaatualiza;
	private String ttarelacidente;
	private String ttaativo;
	private List<OcorrenciaAcidente> ocorrenciasAcidente = new ArrayList<OcorrenciaAcidente>();

	@OneToMany(mappedBy="tipoAcidente",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<OcorrenciaAcidente> getOcorrenciaAcidente() {
		return ocorrenciasAcidente;
	}

	public void setOcorrenciaAcidente(List<OcorrenciaAcidente> ocorrenciasAcidente) {
		this.ocorrenciasAcidente = ocorrenciasAcidente;
	}
	
	@Column(name = "ttacodigo")
	public Integer getTtacodigo() {
		return this.ttacodigo;
	}

	public void setTtacodigo(Integer ttacodigo) {
		this.ttacodigo = ttacodigo;
	}

	@Column(name = "ttadescricao", length = 42)
	public String getTtadescricao() {
		return this.ttadescricao;
	}

	public void setTtadescricao(String ttadescricao) {
		this.ttadescricao = ttadescricao;
	}

	@Column(name = "ttaatualiza", length = 1)
	public String getTtaatualiza() {
		return this.ttaatualiza;
	}

	public void setTtaatualiza(String ttaatualiza) {
		this.ttaatualiza = ttaatualiza;
	}

	@Column(name = "ttarelacidente", length = 6)
	public String getTtarelacidente() {
		return this.ttarelacidente;
	}

	public void setTtarelacidente(String ttarelacidente) {
		this.ttarelacidente = ttarelacidente;
	}

	@Column(name = "ttaativo", length = 1)
	public String getTtaativo() {
		return this.ttaativo;
	}

	public void setTtaativo(String ttaativo) {
		this.ttaativo = ttaativo;
	}
}
