package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipopontomedicoId generated by hbm2java
 */
@Entity
public class TipoPontoMedico implements java.io.Serializable {

	private Integer ttmcodigo;
	private String ttmdescricao;
	private String ttmatualiza;


	@Column(name = "ttmcodigo")
	public Integer getTtmcodigo() {
		return this.ttmcodigo;
	}

	public void setTtmcodigo(Integer ttmcodigo) {
		this.ttmcodigo = ttmcodigo;
	}

	@Column(name = "ttmdescricao", length = 14)
	public String getTtmdescricao() {
		return this.ttmdescricao;
	}

	public void setTtmdescricao(String ttmdescricao) {
		this.ttmdescricao = ttmdescricao;
	}

	@Column(name = "ttmatualiza", length = 1)
	public String getTtmatualiza() {
		return this.ttmatualiza;
	}

	public void setTtmatualiza(String ttmatualiza) {
		this.ttmatualiza = ttmatualiza;
	}
}
