package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TiposinalizacaoId generated by hbm2java
 */
@Entity
public class TipoSinalizacao implements java.io.Serializable {

	private Integer ttscodigo;
	private String ttsdescricao;
	private String ttsatualiza;

	@Column(name = "ttscodigo")
	public Integer getTtscodigo() {
		return this.ttscodigo;
	}

	public void setTtscodigo(Integer ttscodigo) {
		this.ttscodigo = ttscodigo;
	}

	@Column(name = "ttsdescricao", length = 27)
	public String getTtsdescricao() {
		return this.ttsdescricao;
	}

	public void setTtsdescricao(String ttsdescricao) {
		this.ttsdescricao = ttsdescricao;
	}

	@Column(name = "ttsatualiza", length = 1)
	public String getTtsatualiza() {
		return this.ttsatualiza;
	}

	public void setTtsatualiza(String ttsatualiza) {
		this.ttsatualiza = ttsatualiza;
	}
}
