package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipoapreensaoId generated by hbm2java
 */
@Entity
public class TipoApreensao implements java.io.Serializable {

	private Integer ttpcodigo;
	private String ttpdescricao;
	private String ttpatualiza;

	@Column(name = "ttpcodigo")
	public Integer getTtpcodigo() {
		return this.ttpcodigo;
	}

	public void setTtpcodigo(Integer ttpcodigo) {
		this.ttpcodigo = ttpcodigo;
	}

	@Column(name = "ttpdescricao", length = 22)
	public String getTtpdescricao() {
		return this.ttpdescricao;
	}

	public void setTtpdescricao(String ttpdescricao) {
		this.ttpdescricao = ttpdescricao;
	}

	@Column(name = "ttpatualiza", length = 1)
	public String getTtpatualiza() {
		return this.ttpatualiza;
	}

	public void setTtpatualiza(String ttpatualiza) {
		this.ttpatualiza = ttpatualiza;
	}
}
