package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * TipounidadeoperacionalId generated by hbm2java
 */
@Entity
public class TipoUnidadeOperacional implements java.io.Serializable {

	private Integer ttucodigo;
	private String ttudescricao;
	private String ttuatualiza;
	private List<UnidadeOperacional> unidadesOperacional = new ArrayList<UnidadeOperacional>();
	
	
    @OneToMany(mappedBy="tipoUnidadeOperacional",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<UnidadeOperacional> getUnidadesOperacional() {
		return unidadesOperacional;
	}

	public void setUnidadesOperacional(List<UnidadeOperacional> unidadesOperacional) {
		this.unidadesOperacional = unidadesOperacional;
	}

	@Column(name = "ttucodigo")
	public Integer getTtucodigo() {
		return this.ttucodigo;
	}

	public void setTtucodigo(Integer ttucodigo) {
		this.ttucodigo = ttucodigo;
	}

	@Column(name = "ttudescricao", length = 46)
	public String getTtudescricao() {
		return this.ttudescricao;
	}

	public void setTtudescricao(String ttudescricao) {
		this.ttudescricao = ttudescricao;
	}

	@Column(name = "ttuatualiza", length = 1)
	public String getTtuatualiza() {
		return this.ttuatualiza;
	}

	public void setTtuatualiza(String ttuatualiza) {
		this.ttuatualiza = ttuatualiza;
	}
}
