package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipopontonotavelId generated by hbm2java
 */
@Entity
public class TipoPontoNotavel implements java.io.Serializable {

	private Integer ttncodigo;
	private String ttndescricao;
	private String ttnatualiza;

	@Column(name = "ttncodigo")
	public Integer getTtncodigo() {
		return this.ttncodigo;
	}

	public void setTtncodigo(Integer ttncodigo) {
		this.ttncodigo = ttncodigo;
	}

	@Column(name = "ttndescricao", length = 34)
	public String getTtndescricao() {
		return this.ttndescricao;
	}

	public void setTtndescricao(String ttndescricao) {
		this.ttndescricao = ttndescricao;
	}

	@Column(name = "ttnatualiza", length = 1)
	public String getTtnatualiza() {
		return this.ttnatualiza;
	}

	public void setTtnatualiza(String ttnatualiza) {
		this.ttnatualiza = ttnatualiza;
	}
}
