package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipodocumentoId generated by hbm2java
 */
@Entity
public class TipoDocumento implements java.io.Serializable {

	private Integer ttocodigo;
	private String ttodescricao;
	private String ttoatualiza;
	private String ttorelapreensao;
	private String ttorelrecuperacao;

	@Column(name = "ttocodigo")
	public Integer getTtocodigo() {
		return this.ttocodigo;
	}

	public void setTtocodigo(Integer ttocodigo) {
		this.ttocodigo = ttocodigo;
	}

	@Column(name = "ttodescricao", length = 32)
	public String getTtodescricao() {
		return this.ttodescricao;
	}

	public void setTtodescricao(String ttodescricao) {
		this.ttodescricao = ttodescricao;
	}

	@Column(name = "ttoatualiza", length = 1)
	public String getTtoatualiza() {
		return this.ttoatualiza;
	}

	public void setTtoatualiza(String ttoatualiza) {
		this.ttoatualiza = ttoatualiza;
	}

	@Column(name = "ttorelapreensao", length = 6)
	public String getTtorelapreensao() {
		return this.ttorelapreensao;
	}

	public void setTtorelapreensao(String ttorelapreensao) {
		this.ttorelapreensao = ttorelapreensao;
	}

	@Column(name = "ttorelrecuperacao", length = 6)
	public String getTtorelrecuperacao() {
		return this.ttorelrecuperacao;
	}

	public void setTtorelrecuperacao(String ttorelrecuperacao) {
		this.ttorelrecuperacao = ttorelrecuperacao;
	}
}
