package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * TipoenvolvidoId generated by hbm2java
 */
@Entity
public class TipoEnvolvido implements java.io.Serializable {

	private Integer ttecodigo;
	private String ttedescricao;
	private String tteatualiza;
	private String tteativo;
	private List<OcorrenciaPessoa> ocorrenciasPessoa = new ArrayList<OcorrenciaPessoa>();

	
	@OneToMany(mappedBy = "tipoEnvolvido",fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<OcorrenciaPessoa> getOcorrenciasPessoa() {
		return ocorrenciasPessoa;
	}

	public void setOcorrenciasPessoa(List<OcorrenciaPessoa> ocorrenciasPessoa) {
		this.ocorrenciasPessoa = ocorrenciasPessoa;
	}

	
	

	@Column(name = "ttecodigo")
	public Integer getTtecodigo() {
		return this.ttecodigo;
	}

	
	public void setTtecodigo(Integer ttecodigo) {
		this.ttecodigo = ttecodigo;
	}

	@Column(name = "ttedescricao", length = 25)
	public String getTtedescricao() {
		return this.ttedescricao;
	}

	public void setTtedescricao(String ttedescricao) {
		this.ttedescricao = ttedescricao;
	}

	@Column(name = "tteatualiza", length = 1)
	public String getTteatualiza() {
		return this.tteatualiza;
	}

	public void setTteatualiza(String tteatualiza) {
		this.tteatualiza = tteatualiza;
	}

	@Column(name = "tteativo", length = 1)
	public String getTteativo() {
		return this.tteativo;
	}

	public void setTteativo(String tteativo) {
		this.tteativo = tteativo;
	}
}
