package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * TipodetencaoId generated by hbm2java
 */
@Entity
public class TipoDetencao implements java.io.Serializable {

	private Integer ttdcodigo;
	private String ttddescricao;
	private String ttdatualiza;
	private String ttdrelacidente;


	@Column(name = "ttdcodigo")
	public Integer getTtdcodigo() {
		return this.ttdcodigo;
	}

	public void setTtdcodigo(Integer ttdcodigo) {
		this.ttdcodigo = ttdcodigo;
	}

	@Column(name = "ttddescricao", length = 29)
	public String getTtddescricao() {
		return this.ttddescricao;
	}

	public void setTtddescricao(String ttddescricao) {
		this.ttddescricao = ttddescricao;
	}

	@Column(name = "ttdatualiza", length = 1)
	public String getTtdatualiza() {
		return this.ttdatualiza;
	}

	public void setTtdatualiza(String ttdatualiza) {
		this.ttdatualiza = ttdatualiza;
	}

	@Column(name = "ttdrelacidente", length = 6)
	public String getTtdrelacidente() {
		return this.ttdrelacidente;
	}

	public void setTtdrelacidente(String ttdrelacidente) {
		this.ttdrelacidente = ttdrelacidente;
	}
}
