package br.com.ocorrenciasbr.model;

// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * UfId generated by hbm2java
 */
@Entity
public class Uf implements java.io.Serializable {

	private String tufuf;
	private String tufdenominacao;

	@Column(name = "tufuf", length = 2)
	public String getTufuf() {
		return this.tufuf;
	}

	public void setTufuf(String tufuf) {
		this.tufuf = tufuf;
	}

	@Column(name = "tufdenominacao", length = 19)
	public String getTufdenominacao() {
		return this.tufdenominacao;
	}

	public void setTufdenominacao(String tufdenominacao) {
		this.tufdenominacao = tufdenominacao;
	}
}
