package br.com.ocorrenciasbr.model;
// Generated Sep 16, 2013 3:34:01 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * VeiculoId generated by hbm2java
 */
@Entity
public class Veiculo  implements java.io.Serializable {


     private String veiid;
     private String veiveiano;
     private String veitmvcodigo;
     private String veiqtdocupantes;
     private String veitevcodigo;
     private String veitcvcodigo;
     private String veitvvcodigo;
     private String veidescricao;
     private String veimunicipio;
     private String veitcecodigo;
     private String veimunorigem;
     private String veipaisorigem;
     private String veimundestino;
     private String veipaisdestino;
     private String veitttcodigo;
     private String veitipoproprietario;
     private String veiproprietario;
     private String veioenid;
     private String veisequencial;
     private String veitipoplaca;
     
     private Pessoa pessoa;
     private OcorrenciaVeiculo ocorrenciaVeiculo;

     
    @ManyToOne
    @JoinColumn(name="ocvveiid")
    public OcorrenciaVeiculo getOcorrenciaVeiculo() {
		return ocorrenciaVeiculo;
	}

	public void setOcorrenciaVeiculo(OcorrenciaVeiculo ocorrenciaVeiculo) {
		this.ocorrenciaVeiculo = ocorrenciaVeiculo;
	}

	@OneToOne
	@JoinColumn(name="pesveiid")
    public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name="veiid", length=10)
    public String getVeiid() {
        return this.veiid;
    }
    
    public void setVeiid(String veiid) {
        this.veiid = veiid;
    }


    @Column(name="veiveiano", length=10)
    public String getVeiveiano() {
        return this.veiveiano;
    }
    
    public void setVeiveiano(String veiveiano) {
        this.veiveiano = veiveiano;
    }


    @Column(name="veitmvcodigo", length=10)
    public String getVeitmvcodigo() {
        return this.veitmvcodigo;
    }
    
    public void setVeitmvcodigo(String veitmvcodigo) {
        this.veitmvcodigo = veitmvcodigo;
    }


    @Column(name="veiqtdocupantes", length=10)
    public String getVeiqtdocupantes() {
        return this.veiqtdocupantes;
    }
    
    public void setVeiqtdocupantes(String veiqtdocupantes) {
        this.veiqtdocupantes = veiqtdocupantes;
    }


    @Column(name="veitevcodigo", length=10)
    public String getVeitevcodigo() {
        return this.veitevcodigo;
    }
    
    public void setVeitevcodigo(String veitevcodigo) {
        this.veitevcodigo = veitevcodigo;
    }


    @Column(name="veitcvcodigo", length=10)
    public String getVeitcvcodigo() {
        return this.veitcvcodigo;
    }
    
    public void setVeitcvcodigo(String veitcvcodigo) {
        this.veitcvcodigo = veitcvcodigo;
    }


    @Column(name="veitvvcodigo", length=10)
    public String getVeitvvcodigo() {
        return this.veitvvcodigo;
    }
    
    public void setVeitvvcodigo(String veitvvcodigo) {
        this.veitvvcodigo = veitvvcodigo;
    }


    @Column(name="veidescricao", length=10)
    public String getVeidescricao() {
        return this.veidescricao;
    }
    
    public void setVeidescricao(String veidescricao) {
        this.veidescricao = veidescricao;
    }


    @Column(name="veimunicipio", length=10)
    public String getVeimunicipio() {
        return this.veimunicipio;
    }
    
    public void setVeimunicipio(String veimunicipio) {
        this.veimunicipio = veimunicipio;
    }


    @Column(name="veitcecodigo", length=10)
    public String getVeitcecodigo() {
        return this.veitcecodigo;
    }
    
    public void setVeitcecodigo(String veitcecodigo) {
        this.veitcecodigo = veitcecodigo;
    }


    @Column(name="veimunorigem", length=10)
    public String getVeimunorigem() {
        return this.veimunorigem;
    }
    
    public void setVeimunorigem(String veimunorigem) {
        this.veimunorigem = veimunorigem;
    }


    @Column(name="veipaisorigem", length=10)
    public String getVeipaisorigem() {
        return this.veipaisorigem;
    }
    
    public void setVeipaisorigem(String veipaisorigem) {
        this.veipaisorigem = veipaisorigem;
    }


    @Column(name="veimundestino", length=10)
    public String getVeimundestino() {
        return this.veimundestino;
    }
    
    public void setVeimundestino(String veimundestino) {
        this.veimundestino = veimundestino;
    }


    @Column(name="veipaisdestino", length=10)
    public String getVeipaisdestino() {
        return this.veipaisdestino;
    }
    
    public void setVeipaisdestino(String veipaisdestino) {
        this.veipaisdestino = veipaisdestino;
    }


    @Column(name="veitttcodigo", length=10)
    public String getVeitttcodigo() {
        return this.veitttcodigo;
    }
    
    public void setVeitttcodigo(String veitttcodigo) {
        this.veitttcodigo = veitttcodigo;
    }


    @Column(name="veitipoproprietario", length=10)
    public String getVeitipoproprietario() {
        return this.veitipoproprietario;
    }
    
    public void setVeitipoproprietario(String veitipoproprietario) {
        this.veitipoproprietario = veitipoproprietario;
    }


    @Column(name="veiproprietario", length=10)
    public String getVeiproprietario() {
        return this.veiproprietario;
    }
    
    public void setVeiproprietario(String veiproprietario) {
        this.veiproprietario = veiproprietario;
    }


    @Column(name="veioenid", length=10)
    public String getVeioenid() {
        return this.veioenid;
    }
    
    public void setVeioenid(String veioenid) {
        this.veioenid = veioenid;
    }


    @Column(name="veisequencial", length=10)
    public String getVeisequencial() {
        return this.veisequencial;
    }
    
    public void setVeisequencial(String veisequencial) {
        this.veisequencial = veisequencial;
    }


    @Column(name="veitipoplaca", length=10)
    public String getVeitipoplaca() {
        return this.veitipoplaca;
    }
    
    public void setVeitipoplaca(String veitipoplaca) {
        this.veitipoplaca = veitipoplaca;
    }
}


